import json
import os
from clang.cindex import Index, CursorKind, Config

# Adjust if libclang isn't in your default path
# Config.set_library_path("/usr/lib/llvm-15/lib/")

# Strings you care about
TARGET_STRINGS = {"HTTP", "FTP", "LDAP", "DICT", "TELNET"}

def find_string_literals(node, active_macros=None):
    """Recursively walk the AST to find string literals under #ifdef/#ifndef guards."""
    results = []

    # # Handle conditional compilation nodes
    # if node.kind in (CursorKind.IFDEF, CursorKind.IFNDEF):
    #     macro = node.displayname
    #     negated = (node.kind == CursorKind.IFNDEF)
    #     new_active = (active_macros or []) + [(macro, negated)]
    #     for c in node.get_children():
    #         results.extend(find_string_literals(c, new_active))
    #     return results

    # String literal
    if node.kind == CursorKind.STRING_LITERAL:
        val = node.spelling.strip('"')
        print(val)
        if val in TARGET_STRINGS:
            results.append((val, active_macros or []))

    # Recurse
    for c in node.get_children():
        results.extend(find_string_literals(c, active_macros))
    return results


def analyze_file(path, clang_args):
    """Parse one file with libclang and return string→macro mappings."""
    index = Index.create()
    # tu = index.parse(path, args=clang_args)
    print(clang_args)
    print(path)
    tu = index.parse(path, args=['-DBUILDING_LIBCURL', '-DCURL_HIDDEN_SYMBOLS', '-DHAVE_CONFIG_H', '-Dlibcurl_EXPORTS', '-I/root/buildroot/buildroot-2025.02.4/output/build/libcurl-7.71.1/include', '-I/root/buildroot/buildroot-2025.02.4/output/build/libcurl-7.71.1/lib/../include', '-I/root/buildroot/buildroot-2025.02.4/output/build/libcurl-7.71.1/lib/..', '-I/root/buildroot/buildroot-2025.02.4/output/build/libcurl-7.71.1/lib', '-pedantic', '-Wall', '-W', '-Wpointer-arith', '-Wwrite-strings', '-Wunused', '-Wshadow', '-Winline', '-Wnested-externs', '-Wmissing-declarations', '-Wmissing-prototypes', '-Wno-long-long', '-Wfloat-equal', '-Wno-multichar', '-Wsign-compare', '-Wundef', '-Wno-format-nonliteral', '-Wendif-labels', '-Wstrict-prototypes', '-Wdeclaration-after-statement', '-Wstrict-aliasing=3', '-Wcast-align', '-Wtype-limits', '-Wold-style-declaration', '-Wmissing-parameter-type', '-Wempty-body', '-Wclobbered', '-Wignored-qualifiers', '-Wconversion', '-Wno-sign-conversion', '-Wvla', '-Wdouble-promotion', '-Wno-system-headers', '-Wno-pedantic-ms-format', '-fPIC', '-fvisibility=hidden'])
    if not tu:
        print("PROBLEM")
        return []
    return find_string_literals(tu.cursor)


def main():
    # Load compile_commands.json (generated by cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON)
    with open("compile_commands.json") as f:
        db = json.load(f)

    results = {}  # map: string → list of macros
    for entry in db:
        file_path = entry["file"]
        args = entry.get("arguments") or entry.get("command").split()

        # Remove compiler executable
        if args and not args[0].startswith("-"):
            args = args[1:]
        file_results = analyze_file("lib/ftp.c", args)
        break
        for string, macros in file_results:
            results.setdefault(string, set()).update(macros)

    # Print summary
    for string, macros in results.items():
        print(f"\nString '{string}' appears under:")
        for macro, neg in macros:
            print(f"   {'!' if neg else ''}{macro}")


if __name__ == "__main__":
    main()
